sudo: required
services:
  - docker
language: python               # Add language specification
python:                        # Specify Python version
  - "3.8"                      # Use Python 3.8 or later
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-408717
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t okitsnotok/react-test -f ./client/Dockerfile.dev ./client
  - export CLOUDSDK_PYTHON=$(which python3)

script:
  - docker run -e CI=true okitsnotok/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master